"""
lint_validator.py

Simple syntax checker for Python files generated by AISuite codegen.
"""

import subprocess
import os

def validate_python_file(filepath):
    try:
        subprocess.check_output(["python", "-m", "py_compile", filepath])
        print(f"✔️ Syntax OK: {filepath}")
    except subprocess.CalledProcessError:
        print(f"❌ Syntax Error: {filepath}")

def validate_directory(directory):
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(".py"):
                validate_python_file(os.path.join(root, file))

if __name__ == "__main__":
    validate_directory("output")
